version: '3'
services:
  web:
    container_name: amss_inventory
    build: ./docker
  #  restart: always
    ports:
    - "8000:80"
    volumes:
    - .:/var/www/amss_inventory
    links:
    - db
    - redis
  redis:
    container_name: amss_inventory_redis
    image: "redis:alpine"
    ports:
    - "6839:6379"
  db:
    container_name: amss_inventory_db
    image: "mariadb:10.3.22"
  #  restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: "amss_inventory"
    ports:
    - "3360:3306"
